export const CMS_STATE_IDS: Record<string, number> = {
  alabama: 1,
  alaska: 2,
  arizona: 3,
  arkansas: 4,
  california: 5,
  colorado: 6,
  connecticut: 7,
  delaware: 8,
  'district of columbia': 9,
  florida: 10,
  georgia: 11,
  hawaii: 12,
  idaho: 13,
  illinois: 14,
  indiana: 15,
  iowa: 16,
  kansas: 17,
  kentucky: 18,
  louisiana: 19,
  maine: 20,
  maryland: 21,
  massachusetts: 22,
  michigan: 23,
  minnesota: 24,
  mississippi: 25,
  missouri: 26,
  montana: 27,
  nebraska: 28,
  nevada: 29,
  'new hampshire': 30,
  'new jersey': 31,
  'new mexico': 32,
  'new york': 33,
  'north carolina': 34,
  'north dakota': 35,
  ohio: 36,
  oklahoma: 37,
  oregon: 38,
  pennsylvania: 39,
  'rhode island': 40,
  'south carolina': 41,
  'south dakota': 42,
  tennessee: 43,
  texas: 44,
  utah: 45,
  vermont: 46,
  virginia: 47,
  washington: 48,
  'west virginia': 49,
  wisconsin: 50,
  wyoming: 51,
  'puerto rico': 52,
  'virgin islands': 53,
  guam: 54,
  'american samoa': 55,
  'northern mariana islands': 56,
}

const USPS_ABBR: Record<string, string> = {
  al: 'alabama',
  ak: 'alaska',
  az: 'arizona',
  ar: 'arkansas',
  ca: 'california',
  co: 'colorado',
  ct: 'connecticut',
  de: 'delaware',
  dc: 'district of columbia',
  fl: 'florida',
  ga: 'georgia',
  hi: 'hawaii',
  id: 'idaho',
  il: 'illinois',
  in: 'indiana',
  ia: 'iowa',
  ks: 'kansas',
  ky: 'kentucky',
  la: 'louisiana',
  me: 'maine',
  md: 'maryland',
  ma: 'massachusetts',
  mi: 'michigan',
  mn: 'minnesota',
  ms: 'mississippi',
  mo: 'missouri',
  mt: 'montana',
  ne: 'nebraska',
  nv: 'nevada',
  nh: 'new hampshire',
  nj: 'new jersey',
  nm: 'new mexico',
  ny: 'new york',
  nc: 'north carolina',
  nd: 'north dakota',
  oh: 'ohio',
  ok: 'oklahoma',
  or: 'oregon',
  pa: 'pennsylvania',
  ri: 'rhode island',
  sc: 'south carolina',
  sd: 'south dakota',
  tn: 'tennessee',
  tx: 'texas',
  ut: 'utah',
  vt: 'vermont',
  va: 'virginia',
  wa: 'washington',
  wv: 'west virginia',
  wi: 'wisconsin',
  wy: 'wyoming',
  pr: 'puerto rico',
  vi: 'virgin islands',
  gu: 'guam',
  as: 'american samoa',
  mp: 'northern mariana islands',
}

export function resolveCmsStateId(stateName: string): number | null {
  const key = stateName.toLowerCase().trim()
  if (!key) return null
  if (CMS_STATE_IDS[key] != null) return CMS_STATE_IDS[key]
  if (USPS_ABBR[key] != null) return CMS_STATE_IDS[USPS_ABBR[key]] ?? null
  for (const [name, id] of Object.entries(CMS_STATE_IDS)) {
    if (name === key || name.includes(key) || key.includes(name)) return id
  }
  return null
}
