name: Deploy AI-AUG-1 (No Dockerfile)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Corepack
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Enable Corepack and activate Yarn 3.5.1
        run: |
          corepack enable
          corepack prepare yarn@3.5.1 --activate

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "node_modules/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AI-AUG-1'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_236184435CBC4E449B6928B59870D929 }}
          package: release.zip
          
